name: connectivity_plus_web
description: An implementation for the web platform of the Flutter `connectivity_plus` plugin. This uses the NetworkInformation Web API, with a fallback to Navigator.onLine.
version: 1.2.5
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ConnectivityPlusPlugin
        fileName: connectivity_plus_web.dart

dependencies:
  connectivity_plus_platform_interface: ^1.2.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  test: ^1.21.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
